components:
  schemas:
    Superheroe:
      type: object
      required:
        - id
        - name
        - power
      properties:
        id:
          type: integer
          example: 1
          description: ID único del superhéroe
        name:
          type: string
          example: "Superman"
          description: Nombre del superhéroe
        power:
          type: string
          example: "Vuelo, Super Fuerza"
          description: Descripción de poderes

  responses:
    NotFound:
      description: Recurso no encontrado
      content:
        application/json:
          schema:
            type: object
            properties:
              mensaje:
                type: string
                example: "No hay supers disponibles"
    BadRequest:
      description: Petición inválida
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Objeto superheroe inválido"

paths:
  /supers:
    get:
      tags:
        - Supers
      summary: Obtener lista de todos los supers
      responses:
        '200':
          description: Lista de superhéroes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Superheroe'
        '404':
          $ref: '#/components/responses/NotFound'

  /supers/{id}:
    get:
      tags:
        - Supers
      summary: Obtener un super por id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID del superhéroe
      responses:
        '200':
          description: Superhéroe encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superheroe'
        '404':
          $ref: '#/components/responses/NotFound'

  /supers/alta:
    post:
      tags:
        - Supers
      summary: Crear un nuevo super
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - power
              properties:
                name:
                  type: string
                  example: "Cyborg"
                power:
                  type: string
                  example: "Tecnología"
      responses:
        '201':
          description: Super creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Superheroe'
        '400':
          $ref: '#/components/responses/BadRequest'